// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM3llq-WOxgAzji7qrafRVf4hLoBch-Cw',
    appId: '1:763464398086:web:9d60780f4eb15f0a09da87',
    messagingSenderId: '763464398086',
    projectId: 'carros-6606a',
    authDomain: 'carros-6606a.firebaseapp.com',
    storageBucket: 'carros-6606a.appspot.com',
    measurementId: 'G-ZPMEHVDT06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKyU_xf-Hu1Zzn1It__BdxwYtnLCrN3FA',
    appId: '1:763464398086:android:5ee7ebb406dc570609da87',
    messagingSenderId: '763464398086',
    projectId: 'carros-6606a',
    storageBucket: 'carros-6606a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAXcY85CPEN8doSROLkuof-Sz_RZongis',
    appId: '1:763464398086:ios:6285c9882302a41309da87',
    messagingSenderId: '763464398086',
    projectId: 'carros-6606a',
    storageBucket: 'carros-6606a.appspot.com',
    androidClientId: '763464398086-rqk784q9h7m2hneocf3rjql01i9mlt6o.apps.googleusercontent.com',
    iosClientId: '763464398086-ebnvk45ha6g53p9kh4nsrpm988u27ir2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carros',
  );
}
